import { useMemo, useState } from "react";
import { ArrowsClockwise, Bell, Buildings, CalendarDots, CaretDown, CaretRight, ChartLineUp, CheckCircle, ClockCountdown, Crosshair, Database, FileText, Funnel, GearSix, MagnifyingGlass, MapPin, Network, Package, Path, Plus, SignOut, SlidersHorizontal, Truck, Warning, X } from "@phosphor-icons/react";

const candidates = [
  { id: 1, priority: "高", from: "東京A社・城南ルート", pair: "東京B社・城南ルート", rate: "46%", next: "78%", merge: "3便を2便に統合", company: "東京A社＋東京B社", depot: "平和島センター", area: "世田谷区・目黒区・品川区", distance: "68km → 44km", driver: "佐藤 健一 / 鈴木 裕介" },
  { id: 2, priority: "高", from: "埼玉C社・さいたま北", pair: "埼玉D社・越谷ルート", rate: "52%", next: "81%", merge: "4便を2便に統合", company: "埼玉C社＋埼玉D社", depot: "戸田共同拠点", area: "さいたま市・越谷市", distance: "92km → 61km", driver: "田中 雅也 / 高橋 遼" },
  { id: 3, priority: "中", from: "千葉E社・千葉西", pair: "千葉F社・船橋ルート", rate: "49%", next: "76%", merge: "3便を2便に統合", company: "千葉E社＋千葉F社", depot: "市川クロスドック", area: "市川市・船橋市・浦安市", distance: "74km → 55km", driver: "森川 誠 / 小林 翼" },
  { id: 4, priority: "中", from: "神奈川G社・横浜北", pair: "神奈川H社・川崎", rate: "53%", next: "79%", merge: "3便を2便に統合", company: "神奈川G社＋神奈川H社", depot: "川崎共同拠点", area: "横浜市・川崎市", distance: "83km → 59km", driver: "伊藤 翔 / 山本 和也" },
];
const nav = [["live","ライブ管制",Crosshair],["plan","配送計画",CalendarDots],["operations","例外対応",Warning],["companies","会社・車両",Buildings],["reports","実績レポート",ChartLineUp],["architecture","システム構成",Network]];

function Sidebar({page,setPage}){return <aside className="sidebar"><div className="brand"><span className="brand-mark">GO</span><span>物流</span></div><nav aria-label="主要メニュー">{nav.map(([id,label,Icon])=><button key={id} className={page===id?"nav-item active":"nav-item"} onClick={()=>setPage(id)} aria-current={page===id?"page":undefined}><Icon size={21} weight={page===id?"fill":"regular"}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><GearSix size={21}/><span>設定</span></button><button className="nav-item"><SignOut size={21}/><span>ログアウト</span></button></div></aside>}
function Topbar(){return <header className="topbar"><div className="product-name">共同配車コントロールタワー</div><div className="top-actions"><span>2026年8月21日（金）</span><span className="sync"><ArrowsClockwise size={14}/> 自動更新中</span><button className="icon-button" aria-label="通知"><Bell size={20}/><span className="notification">8</span></button><div className="user"><span className="avatar">山</span><div><b>山田 太郎</b><small>中央配車センター</small></div><CaretDown size={14}/></div></div></header>}
function Metric({icon:Icon,label,value,unit,accent}){return <div className="metric"><Icon size={20}/><div><span>{label}</span><strong className={accent?"accent":""}>{value}<small>{unit}</small></strong></div></div>}
function AppHeader({title,subtitle}){return <div className="app-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="header-metrics"><Metric icon={Buildings} label="参加会社" value="30" unit="社"/><Metric icon={Truck} label="稼働車両" value="602" unit="台"/><Metric icon={Package} label="本日の配送" value="1,254" unit="件"/><Metric icon={ChartLineUp} label="共同配送率" value="68" unit="%" accent/></div></div>}

function CandidateList({selected,setSelected}){const[query,setQuery]=useState("");const[filterOpen,setFilterOpen]=useState(false);const visible=candidates.filter(c=>`${c.from}${c.pair}`.includes(query));return <section className="candidate-panel"><div className="section-title"><div><b>共同配送候補</b><span>12件</span></div><button className="link-button">すべて表示</button></div><div className="filter-row"><label className="search"><MagnifyingGlass size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="会社・ルートを検索"/></label><button className={filterOpen?"filter-button active":"filter-button"} onClick={()=>setFilterOpen(v=>!v)}><Funnel size={16}/></button></div>{filterOpen&&<div className="filter-popover"><b>優先度</b><label><input type="checkbox" defaultChecked/> 高</label><label><input type="checkbox" defaultChecked/> 中</label><label><input type="checkbox"/> 低</label></div>}<div className="candidate-list">{visible.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={selected===c.id?"candidate selected":"candidate"}><div className="candidate-top"><span className={`priority p-${c.priority}`}>{c.priority}</span><small>10:{16-c.id*2} 更新</small></div><div className="route-name"><span className="package-dot"><Package size={17} weight="fill"/></span><div><b>{c.from}</b><span>{c.pair}</span></div><CaretRight size={16}/></div><div className="candidate-impact"><span>積載率 <b>{c.rate}</b></span><span>→</span><strong>{c.next}</strong></div><p>{c.merge}</p></button>)}</div></section>}
function TripBlock({icon:Icon,tone,name,depot,area,driver}){return <div className="trip-block"><div className="trip-title"><span className={`trip-icon ${tone}`}><Icon size={17} weight="fill"/></span><b>{name}</b><span>3便</span></div><dl><div><dt>出発地</dt><dd>{depot}</dd></div><div><dt>配送エリア</dt><dd>{area}</dd></div><div><dt>車両</dt><dd>2tロング 1台</dd></div><div><dt>担当</dt><dd>{driver}</dd></div></dl></div>}
function RouteDetail({candidate,onConfirm}){return <aside className="detail-panel"><div className="detail-head"><div><span className="eyebrow">選択中の統合候補</span><h2>{candidate.company}</h2></div><button className="icon-button" aria-label="閉じる"><X size={18}/></button></div><TripBlock icon={Package} tone="cyan" name={candidate.from} depot={candidate.depot} area={candidate.area} driver={candidate.driver.split(" / ")[0]}/><div className="merge-symbol"><Plus size={20}/></div><TripBlock icon={Truck} tone="blue" name={candidate.pair} depot="大井町センター" area={candidate.area} driver={candidate.driver.split(" / ")[1]}/><div className="proposal"><div className="proposal-title"><CheckCircle size={18} weight="fill"/><b>統合シミュレーション</b><span>実行可能</span></div><div className="big-rate"><span>{candidate.rate}</span><CaretRight size={18}/><strong>{candidate.next}</strong></div><dl><div><dt>削減便数</dt><dd>{candidate.merge}</dd></div><div><dt>走行距離</dt><dd>{candidate.distance}</dd></div><div><dt>推定CO₂</dt><dd>-12.4kg（-18%）</dd></div><div><dt>納品影響</dt><dd className="success-text">時間指定内</dd></div></dl></div><button className="primary-button" onClick={onConfirm}>統合案を確認</button><button className="secondary-button"><SlidersHorizontal size={17}/> 条件を調整</button></aside>}
function LiveControl({notify}){const[selected,setSelected]=useState(1);const candidate=candidates.find(c=>c.id===selected)||candidates[0];const[modal,setModal]=useState(false);return <><AppHeader title="関東ライブ管制" subtitle="関東エリアの配送状況をリアルタイムで監視し、共同配送の機会を逃しません"/><main className="live-layout"><CandidateList selected={selected} setSelected={setSelected}/><section className="map-workspace"><img src="/assets/kanto-live-routes.png" alt="関東エリアの共同配送ルート地図"/><div className="map-status"><span className="live-dot"/> ライブ更新 <b>10:24:15</b></div><div className="map-legend"><span><i className="legend-line blue-line"/>既存ルート</span><span><i className="legend-line cyan-line"/>統合候補</span><span><i className="legend-line amber-line"/>要確認</span></div><div className="map-tools"><button>＋</button><button>−</button><button><Crosshair size={17}/></button></div></section><RouteDetail candidate={candidate} onConfirm={()=>setModal(true)}/></main><div className="bottom-status"><button className="alert-pill"><Warning size={16}/> アラート <b>8件</b><CaretDown size={13}/></button><span>遅延 <b>3件</b></span><span>車両トラブル <b>2件</b></span><span>配送先変更 <b>2件</b></span></div>{modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><div className="confirm-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-icon"><Path size={28}/></div><h2>この統合案を配車計画へ反映しますか？</h2><p>{candidate.company}の対象便を統合し、両社の配車担当者へ承認依頼を送ります。</p><div className="modal-summary"><span>積載率<strong>{candidate.rate} → {candidate.next}</strong></span><span>走行距離<strong>{candidate.distance}</strong></span></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setModal(false)}>キャンセル</button><button className="primary-button" onClick={()=>{setModal(false);notify("統合案を配車計画へ反映しました")}}>承認依頼を送る</button></div></div></div>}</>}

const jobs=["ヤマト産業（株）","東都パーツ（株）","新木場ロジ（株）","城南メタル（株）","羽田テック（株）","相模ロジスティクス（株）"];
function JobRow({name,i}){return <label className="job-row"><input type="checkbox" defaultChecked={i<5}/><span><b>{name}</b><small>{i<3?"江東区新木場":"大田区平和島"}</small></span><em>{5+i*2}箱 / {(1.2+i*.3).toFixed(1)}㎥</em></label>}
function Planning({notify}){const[optimized,setOptimized]=useState(false);const[confirmed,setConfirmed]=useState(false);return <><AppHeader title="8月21日の配送計画" subtitle="30社の案件を横断し、積載・時間帯・車格を満たす共同配送便を組みます"/><main className="planning-page"><section className="jobs-panel"><div className="section-title"><div><b>未割当</b><span>18件</span></div><button className="filter-button"><Funnel size={16}/></button></div><label className="search"><MagnifyingGlass size={16}/><input placeholder="荷主名・品目で検索"/></label><div className="job-group"><h3>江東区新木場 <span>08:00–10:00</span></h3>{jobs.slice(0,3).map((j,i)=><JobRow key={j} name={j} i={i}/>)}</div><div className="job-group"><h3>大田区平和島 <span>10:00–12:00</span></h3>{jobs.slice(3).map((j,i)=><JobRow key={j} name={j} i={i+3}/>)}</div></section><section className="planning-board"><div className="board-head"><div><b>共同配送候補</b><span>時間軸</span></div><button className="secondary-button" onClick={()=>setOptimized(false)}><ArrowsClockwise size={16}/> リセット</button></div><div className="timeline"><div className="time-col">{["07:00","08:00","09:00","10:00","11:00","12:00","13:00"].map(t=><span key={t}>{t}</span>)}</div>{["東京A社 既存便","神奈川B社 既存便",optimized?"共同配送案（統合後）":"統合案を生成"].map((title,col)=><div className={col===2?"route-column proposed":"route-column"} key={title}><h3>{title}</h3>{col===2&&!optimized?<div className="empty-proposal"><Path size={32}/><p>条件を満たす便を選択して<br/>最適化を実行してください</p></div>:<>{jobs.slice(col===0?0:2,col===0?4:6).map((j,i)=><div className={`stop stop-${i+col}`} key={j} style={{top:`${72+i*74}px`}}><b>{8+i}:1{col}</b><span>{j}</span><small>{i+1}.8㎥</small></div>)}{col===2&&optimized&&<div className="route-summary"><b>2便に統合</b><span>積載率 82%</span></div>}</>}</div>)}</div></section><aside className="impact-panel"><h2>統合インパクト</h2><div className="impact-rate"><span>積載率</span><strong>{optimized?"82%":"43%"}</strong><div className={optimized?"bar optimized":"bar"}><i/></div></div><div className="impact-list"><div><span>運行便数</span><b>{optimized?"4便 → 2便":"4便"}</b></div><div><span>総走行距離</span><b>{optimized?"118km（-72km）":"190km"}</b></div><div><span>車両コスト</span><b>{optimized?"¥41,200（-27,100）":"¥68,300"}</b></div><div><span>時間制約</span><b className={optimized?"success-text":""}>{optimized?"すべて適合":"未検証"}</b></div></div><div className="constraint-box"><h3>制約・条件</h3><p><CheckCircle size={16}/> 積載量上限</p><p><CheckCircle size={16}/> ドライバー拘束時間</p><p><CheckCircle size={16}/> 温度帯・混載可否</p></div>{!optimized?<button className="primary-button" onClick={()=>setOptimized(true)}>最適化を実行</button>:<><button className="primary-button" disabled={confirmed} onClick={()=>{setConfirmed(true);notify("共同配送便を確定しました")}}>{confirmed?"確定済み":"共同配送便を確定"}</button><button className="secondary-button"><SlidersHorizontal size={17}/> 条件を調整</button></>}</aside></main></>}

const trips=[["KNT-0842","関東ロジスティクス（株）","葛飾区","08:45","足立共同拠点","江東区・墨田区"],["KNT-0843","丸の内運輸（株）","足立区","09:15","足立共同拠点","川崎市・幸区"],["KNT-0844","京浜物流（株）","川崎区","09:05","川崎共同拠点","横浜市・中区"],["KNT-0845","相模物流（株）","厚木市","08:50","海老名共同拠点","町田市・多摩市"]];
function Operations({notify}){const[resolved,setResolved]=useState(false);return <><AppHeader title="本日の共同配送" subtitle="共同配送便の集荷・集約・納品を追跡し、例外発生時はネットワーク内で振替えます"/><main className="operations-page"><section className="operations-main"><div className="ops-summary"><Metric icon={Truck} label="稼働中" value="42" unit="便" accent/><Metric icon={CheckCircle} label="完了" value="1" unit="便"/><Metric icon={Warning} label="要対応" value={resolved?"2":"3"} unit="件"/><Metric icon={ClockCountdown} label="遅延中" value="4" unit="便"/></div><div className="lane-head"><span>便名・担当</span><span>集荷</span><span>共同拠点</span><span>配送</span></div>{trips.map((t,i)=><div className={i===1&&!resolved?"lane-row alert":"lane-row"} key={t[0]}><div><b>{t[0]}</b><span>{t[1]}</span><small>足立 130 か 56-78</small></div><div><b>{i===1?"08:00":"07:"+(30+i*10)}</b><span>{t[2]}</span><small>{i+2}件 / {3+i}.2t</small></div><div><b>{t[3]}</b><span>{t[4]}</span><small className={i===1&&!resolved?"warning-text":""}>{i===1&&!resolved?"到着遅延 +24分":"到着済み"}</small></div><div><b>10:15–13:00</b><span>{t[5]}</span><small>{5+i}件</small></div><CaretRight size={18}/></div>)}</section><aside className="exception-panel"><div className="eyebrow">要対応の例外　2 / 3</div><span className={resolved?"status-tag resolved":"status-tag"}>{resolved?"解決済み":"到着遅延"}</span><h2>足立共同拠点への到着遅延</h2><strong className="delay">{resolved?"振替手配済み":"到着遅延 +24分"}</strong><dl><div><dt>便名</dt><dd>KNT-0843</dd></div><div><dt>担当会社</dt><dd>丸の内運輸（株）</dd></div><div><dt>現在地</dt><dd>足立区西新井付近</dd></div><div><dt>遅延理由</dt><dd>道路混雑（環七内回り）</dd></div></dl><div className="recovery"><span>自動振替提案</span><h3>川崎便へ振替可能</h3><p><CheckCircle size={18} weight="fill"/> 納品影響なし</p><div className="recovery-flow"><Truck size={23}/><CaretRight size={16}/><MapPin size={23}/><CaretRight size={16}/><Truck size={23}/></div><small>空き容量を使用し、到着見込み 09:56（+5分）</small></div><button className="primary-button" disabled={resolved} onClick={()=>{setResolved(true);notify("振替案を承認し、担当会社へ通知しました")}}>{resolved?"振替案を承認済み":"振替案を承認"}</button><button className="secondary-button">担当会社へ連絡</button></aside></main></>}

const companyNames=["東京A運送","東京Bロジ","埼玉C配送","埼玉D運輸","千葉E物流","千葉Fカーゴ","神奈川G運送","神奈川H急便"];
function Companies(){return <><AppHeader title="会社・車両" subtitle="グループ30社・約600台の稼働状況とデータ連携状態を横断管理します"/><main className="directory-page"><div className="directory-toolbar"><label className="search"><MagnifyingGlass size={16}/><input placeholder="会社名・拠点名で検索"/></label><button className="secondary-button"><Funnel size={16}/> 条件で絞り込み</button><button className="primary-button"><Plus size={17}/> 会社を追加</button></div><div className="company-table"><div className="table-head"><span>会社</span><span>担当エリア</span><span>保有台数</span><span>本日稼働</span><span>平均積載率</span><span>データ連携</span><span/></div>{companyNames.map((n,i)=><div className="table-row" key={n}><span className="company-name"><i>{n.slice(0,1)}</i><b>{n}</b></span><span>{["東京23区南部","東京23区西部","さいたま市","越谷・春日部","千葉市西部","船橋・市川","横浜市北部","川崎市"][i]}</span><span>{18+i%4}台</span><span>{15+i%3}台</span><span><b className="rate-text">{62+i*3}%</b></span><span className="connected"><CheckCircle size={16} weight="fill"/> 正常</span><button className="icon-button"><CaretRight size={17}/></button></div>)}</div></main></>}
function ReportStat({icon:Icon,label,value,note}){return <div><Icon size={24}/><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Reports(){return <><AppHeader title="実績レポート" subtitle="共同配送による稼働改善・原価削減・CO₂削減を会社横断で可視化します"/><main className="reports-page"><div className="report-hero"><div><span>2026年8月度</span><h2>共同配送率</h2><strong>68.4%</strong><small>前月比 +8.2pt</small></div><div className="report-bars">{[42,48,51,53,59,62,68].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><span>{i+2}月</span></div>)}</div></div><div className="report-grid"><ReportStat icon={Truck} label="削減できた運行便" value="1,286便" note="前月比 +18.4%"/><ReportStat icon={Path} label="削減走行距離" value="48,920km" note="地球約1.2周分"/><ReportStat icon={ChartLineUp} label="配送原価削減" value="¥18.6M" note="計画比 104%"/><ReportStat icon={FileText} label="CO₂削減量" value="12.8t" note="前月比 +21.1%"/></div><section className="report-detail"><div><h2>会社別の共同配送率</h2><p>共同配送率の低い会社から改善余地を確認できます。</p></div>{companyNames.slice(0,5).map((n,i)=><div className="company-progress" key={n}><span>{n}</span><div><i style={{width:`${52+i*7}%`}}/></div><b>{52+i*7}%</b></div>)}</section></main></>}
function Architecture(){return <><AppHeader title="システム構成" subtitle="30社の既存システムと車両データを標準化し、最適化・承認・運行フィードバックを一気通貫で接続します"/><main className="architecture-page"><div className="architecture-actions"><div><span className="live-dot"/> 構成バージョン 1.0</div><a className="secondary-button" href="/assets/system-architecture.png" target="_blank" rel="noreferrer"><FileText size={17}/> 画像を開く</a></div><img src="/assets/system-architecture.png" alt="共同配車コントロールタワーのシステムアーキテクチャ"/><div className="architecture-note"><Database size={21}/><div><b>設計の要点</b><span>買収各社のTMSをすぐに置き換えず、API・バッチ・イベント連携で段階的に統合。配車判断と実績を共通データ基盤へ集約します。</span></div></div></main></>}

export function App(){const[page,setPage]=useState("live");const[toast,setToast]=useState("");const notify=message=>{setToast(message);window.setTimeout(()=>setToast(""),3200)};const screen=useMemo(()=>({live:<LiveControl notify={notify}/>,plan:<Planning notify={notify}/>,operations:<Operations notify={notify}/>,companies:<Companies/>,reports:<Reports/>,architecture:<Architecture/>})[page],[page]);return <div className="app-shell"><Sidebar page={page} setPage={setPage}/><div className="app-main"><Topbar/>{screen}</div>{toast&&<div className="toast"><CheckCircle size={20} weight="fill"/>{toast}</div>}</div>}
